FROM golang:1.20-alpine AS build
WORKDIR /src
COPY go.mod ./
COPY cmd/mockoidc ./cmd/mockoidc
RUN CGO_ENABLED=0 go build -o /out/mockoidc ./cmd/mockoidc

FROM alpine:3.19
COPY --from=build /out/mockoidc /usr/local/bin/mockoidc
EXPOSE 8082
ENTRYPOINT ["mockoidc"]
