// Code generated by controller-gen style conventions; maintained manually
// until codegen is wired into CI.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto copies all properties of src into dst.
func (in *AgentSession) DeepCopyInto(out *AgentSession) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

func (in *AgentSession) DeepCopy() *AgentSession {
	out := new(AgentSession)
	in.DeepCopyInto(out)
	return out
}

func (in *AgentSession) DeepCopyObject() runtime.Object { return in.DeepCopy() }

func (in *AgentSessionList) DeepCopyInto(out *AgentSessionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]AgentSession, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}

func (in *AgentSessionList) DeepCopy() *AgentSessionList {
	out := new(AgentSessionList)
	in.DeepCopyInto(out)
	return out
}

func (in *AgentSessionList) DeepCopyObject() runtime.Object { return in.DeepCopy() }

func (in *AgentSessionStatus) DeepCopyInto(out *AgentSessionStatus) {
	*out = *in
	if in.StartedAt != nil {
		t := *in.StartedAt
		out.StartedAt = &t
	}
	if in.LastActivity != nil {
		t := *in.LastActivity
		out.LastActivity = &t
	}
	if in.TerminatedAt != nil {
		t := *in.TerminatedAt
		out.TerminatedAt = &t
	}
}

var (
	_ runtime.Object = (*AgentSession)(nil)
	_ runtime.Object = (*AgentSessionList)(nil)
)
